name: Publish Docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build and publish Docker Image to GitHub Registry
        uses: VaultVulp/gp-docker-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          image-name: AutoWifiLogin